### PR TITLE
SOP creation sop

### PR DESCRIPTION
**Pull request by M-casado**
## Summary
Addition of the SOP to generate other SOP templates based on an SOP request.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change which adds new content)
- [ ] Modified content (non-breaking change which modifies existing content)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Motivation and Context
This SOP aids the repository maintainers (OC/SDPC, T4.3...) to create SOP templates based on SOP requests.

### References
https://github.com/GenomicDataInfrastructure/standard-operating-procedures/issues/9

## Changes Introduced
- Addition of **``GDI-SOP0007``** (_SOP Template creation_)
- Addition of ``images/`` to contain media resources of the repository
- Addition of images and gifs for ``GDI-SOP0007``.

## Review
Not yet reviewed.

## Additional Notes
NA

## Checklist:

**General Compliance:**
- [x] My changes follow the code style of this project ([GDI SOP Style Guide](https://github.com/GenomicDataInfrastructure/standard-operating-procedures/blob/main/docs/GDI-SOP_style-guide.md)) and the file naming conventions of the [file accessioning proposal](https://github.com/GenomicDataInfrastructure/standard-operating-procedures/blob/main/docs//GDI-SOP_sop-accessioning.md).
- [x] I have verified that all new updated content is accessible, including checking that all external references are readable (i.e., no broken links). These may include references to external resources that should be resolvable, and internal references among SOPs.
- [x] I have properly added this PR's changes to the repository [CHANGELOG.md](../CHANGELOG.md).

Only applicable if the PR includes new, or changes to, GDI SOPs (i.e., documents at ``sops/``):
- [x] My SOP-related changes adhere to the [Generic SOP Template](https://github.com/GenomicDataInfrastructure/standard-operating-procedures/blob/main/docs/GDI-SOP_sop-template.md), including format and required fields.
- [x] I have consulted the [Charter](https://github.com/GenomicDataInfrastructure/standard-operating-procedures/blob/main/docs/GDI-SOP_charter.md), [ISM](https://github.com/GenomicDataInfrastructure/standard-operating-procedures/blob/main/docs/GDI-SOP_information-service-management.md), and [ORR](https://github.com/GenomicDataInfrastructure/standard-operating-procedures/blob/main/docs/GDI-SOP_organisational-roles-and-responsibilities.md) documents to ensure compliance. 
- [x] I am complying with the established procedure for SOP creations and modifications, including respecting review phases and notifying needed contributors for reviews.

### CODE REVIEW

**Comment by M-casado** [comment]
For a more convenient review, you can also leave comments that I'll resolve before merging at the Google Document [here](https://docs.google.com/document/d/1OHosT8y3s3YtgzRpJT_6Letzv4beIz9XaI-rrekEVsM/edit#heading=h.dq47koryxshb).

Notice that it's just a copy-paste of the current document as of now. There are format changes, as expected.

**Review by DokaHB — APPROVED** [review]

**Comment by elisavettorstensson** [comment]
I went through the Google document. It is well-written, and it is an excellent first draft of this document. Many procedures are described in this document that one must do in practice to realise if the provided description was good or not or if it needs to include something. There is also so much information that one needs time to understand and become familiar with all this. At that moment, we are talking much more on a theoretical base, and it seems that the description in this document is good. I made some minor recommendations about some things, which you can consider if you want to change.

**Review by elisavettorstensson — APPROVED** [review]
It is well-written! Good job!

**Comment by M-casado** [comment]
Thanks for the review, @elisavettorstensson :) 
I added/responded to your feedback now

**Comment by bhendriksze** [comment]
This document seems very complete, informative, and practical, offering valuable insights. It's clearly structured, making it easy to read and hopefully easy to follow.

**Review by mattiasstromberg — COMMENTED** [review]
Excellent first draft. The only comment I have concerns step 2 (RFC discussion). Would it be better to have some kind of first draft of the SOP template before initializing the RFC discussion? Is the GH request in step 1 enough as a starting point for the discussions in step 2?

**Comment by M-casado** [comment]
Thanks for your reviews, @bhendriksze & @mattiasstromberg

Regarding your comment, Mattias, I completely agree. I initially had in mind that the GH issue would be enough for discussion. Nevertheless, some other groups were creating an RFC pot, where Requests For Comments documents would be added. Based on Dylan's input, this is done for "substantial changes", and the SOPs fall into that.

Therefore I myself would be content with the GH issue alone, but we can at least make use of GH's linking features, by referencing discussions/issues in different repos.

**Comment by jdylan** [comment]
This is an excellent document. 

Re RFCs - I can envisage some SOPs being 'substantial' but also some being minor. I would support the OC/SDPC detemerining that on a case by case basis, as these committees have all relevant actors from the Pillars/nodes included, if that helps reduce some of the administrative the documentation burden for the more simple SOPs? This would only require a decision box being added after the 'Is SOP request valid?' on the 'Yes' with 'Does this SOP represent a 'substantial' change?'.

I think 2 members of each committee should be nominated as initial reviewers so there is a clear responsibility for the review within the relevant committee - they would also be responsible for monitoring the procession of the SOP through the different steps. These could be assigned just after determining if the SOP is valid, or if it is a substantive change (if that is added). 

Re MB review, I would allow MB to request an extension, but also to explicitly indicate that a veto will not be exercised which would terminate the review period immediately and allow the the SOP to procede to Step 6.

**Review by jmenglund — APPROVED** [review]

**Comment by M-casado** [comment]
I'll add the changes, Dylan, in order:

- [ ] Adding decision box on whether the SOP represents a substantial change.
   - I'm thinking that it's pretty subjective, so I may come up with a checklist of reasons as to what it would be considered to be substantial 🤔 
- [ ] A step to nominate/request nominees, from the OC and SDPC, for them to be responsible through the process. 
   - I think rather than reviewers these 4 members (2 from each committee) would be **approvers**, and the person (also an OC/SDPC member) that was assigned the task from the beginning would be the one following it through till the end (development, review, approval, authorization...). 
   - This responsible person could shift if needed (e.g., if on holidays or blocked by something), same with the appointer approvers, through the process.
- [ ] Add both extension and termination of the veto period for the MB.

**Pull request merged**
